version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  testlink:
    image: 'bitnami/testlink:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 80
    ports:
      - '8082:80'
      - '4443:443'
    volumes:
      - 'testlink_data:/bitnami'
    depends_on:
      - mariadb
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    ports:
      - '8081:8080'
    volumes:
      - 'jenkins-data:/var/jenkins_home'

volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  jenkins-data:
    driver: local
