FROM jenkinsci/blueocean:latest

USER root

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apk add --no-cache --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install virtualenv \
    && pip install selenium \
    && pip install unittest-xml-reporting \
    && rm -rf /var/cache/apk/*

USER jenkins